---
fullname: Algebra-tactics
shortname: algebra-tactics
opam_name: coq-mathcomp-algebra-tactics
organization: math-comp
action: true

synopsis: >-
  Experimental reflexive tactics for ring and field expressions

description: |-
  This library provides experimental `ring` and `field` tactics for
  `comRingType` and `fieldType` instances of Mathematical Components.

authors:
- name: Kazuhiko Sakaguchi
  initial: true

opam-file-maintainer: sakaguchi@coins.tsukuba.ac.jp

license:
  fullname: CeCILL-B Free Software License Agreement
  identifier: CECILL-B
  file: CeCILL-B

supported_coq_versions:
  text: 8.13 or later
  opam: '{(>= "8.13" & < "8.15~") | (= "dev")}'

tested_coq_nix_versions:

tested_coq_opam_versions:
- version: '1.12.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: 'coq-8.13'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.14'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'

dependencies:
- opam:
    name: coq-mathcomp-algebra
    version: '{(>= "1.12" & < "1.13~") | (= "dev")}'
  description: |-
    [MathComp](https://math-comp.github.io) 1.12.0 or later
- opam:
    name: coq-mathcomp-zify
    version: '{(>= "1.0.0") | (= "dev")}'
  description: |-
    [Mczify](https://github.com/math-comp/mczify) 1.0.0 or later
- opam:
    name: coq-elpi
    version: '{(>= "1.10.1") | (= "dev")}'
  description: |-
    [Coq-Elpi](https://github.com/LPCIC/coq-elpi) 1.10.1 or later

namespace: mathcomp.algebra_tactics
---
