---
fullname: Algebra Tactics
shortname: algebra-tactics
opam_name: coq-mathcomp-algebra-tactics
organization: math-comp
action: true

synopsis: >-
  Ring and field tactics for Mathematical Components

description: |-
  This library provides `ring` and `field` tactics for Mathematical Components,
  that work with any `comRingType` and `fieldType` instances, respectively.
  Their instance resolution is done through canonical structure inference.
  Therefore, they work with abstract rings and do not require `Add Ring` and
  `Add Field` commands. Another key feature of this library is that they
  automatically push down ring morphisms and additive functions to leaves of
  ring/field expressions before normalization to the Horner form.

authors:
- name: Kazuhiko Sakaguchi
  initial: true

opam-file-maintainer: sakaguchi@coins.tsukuba.ac.jp

license:
  fullname: CeCILL-B Free Software License Agreement
  identifier: CECILL-B
  file: CeCILL-B

supported_coq_versions:
  text: 8.13 or later
  opam: '{>= "8.13"}'

tested_coq_nix_versions:

tested_coq_opam_versions:
- version: '1.12.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.14.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.14.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.14.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.14.0-coq-dev'
  repo: 'mathcomp/mathcomp'
- version: 'coq-8.13'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.14'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.15'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{>= "1.12"}'
  description: |-
    [MathComp](https://math-comp.github.io) ssreflect 1.12 or later
- opam:
    name: coq-mathcomp-algebra
  description: |-
    [MathComp](https://math-comp.github.io) algebra
- opam:
    name: coq-mathcomp-zify
    version: '{>= "1.1.0"}'
  description: |-
    [Mczify](https://github.com/math-comp/mczify) 1.1.0 or later
- opam:
    name: coq-elpi
    version: '{>= "1.10.1"}'
  description: |-
    [Coq-Elpi](https://github.com/LPCIC/coq-elpi) 1.10.1 or later

namespace: mathcomp.algebra_tactics

documentation: |-
  ## Credits
  The way we adapt the internals of Coq's `ring` and `field` tactics to
  algebraic structures of the Mathematical Components library is inspired by the
  [elliptic-curves-ssr](https://github.com/strub/elliptic-curves-ssr) library by
  Evmorfia-Iro Bartzia and Pierre-Yves Strub.

---
