---
fullname: Algebra Tactics
shortname: algebra-tactics
opam_name: coq-mathcomp-algebra-tactics
organization: math-comp
action: true

synopsis: >-
  Ring and field tactics for Mathematical Components

description: |-
  This library provides `ring`, `field`, and `lra` tactics for Mathematical
  Components, that work with any `comRingType`, `fieldType`, and
  `realDomainType` or `realFieldType` instances, respectively. Their instance
  resolution is done through canonical structure inference.  Therefore, they
  work with abstract rings and do not require `Add Ring` and `Add Field`
  commands. Another key feature of this library is that they automatically push
  down ring morphisms and additive functions to leaves of ring/field expressions
  before applying the proof procedures.

publications:
- pub_url: https://drops.dagstuhl.de/opus/volltexte/2022/16738/
  pub_title: Reflexive tactics for algebra, revisited
  pub_doi: 10.4230/LIPIcs.ITP.2022.29

authors:
- name: Kazuhiko Sakaguchi
  initial: true

opam-file-maintainer: kazuhiko.sakaguchi@inria.fr

license:
  fullname: CeCILL-B Free Software License Agreement
  identifier: CECILL-B
  file: CeCILL-B

supported_coq_versions:
  text: 8.16 or later
  opam: '{>= "8.16"}'

tested_coq_nix_versions:

tested_coq_opam_versions:
- version: '1.15.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '1.16.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '1.16.0-coq-8.17'
  repo: 'mathcomp/mathcomp'
- version: 'coq-8.16'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.17'
  repo: 'mathcomp/mathcomp-dev'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{>= "1.15"}'
  description: |-
    [MathComp](https://math-comp.github.io) ssreflect 1.15 or later
- opam:
    name: coq-mathcomp-algebra
  description: |-
    [MathComp](https://math-comp.github.io) algebra
- opam:
    name: coq-mathcomp-zify
    version: '{>= "1.1.0"}'
  description: |-
    [Mczify](https://github.com/math-comp/mczify) 1.1.0 or later
- opam:
    name: coq-elpi
    version: '{>= "1.15.0" & != "1.17.0"}'
  description: |-
    [Coq-Elpi](https://github.com/LPCIC/coq-elpi) 1.15.0 or later (known not to work with 1.17.0)

namespace: mathcomp.algebra_tactics

documentation: |-
  ## Credits

  - The way we adapt the internals of Coq's `ring` and `field` tactics to
    algebraic structures of the Mathematical Components library is inspired by
    the [elliptic-curves-ssr](https://github.com/strub/elliptic-curves-ssr)
    library by Evmorfia-Iro Bartzia and Pierre-Yves Strub.
  - The example [`from_sander.v`](examples/from_sander.v) contributed by Assia
    Mahboubi was given to her by [Sander Dahmen](http://www.few.vu.nl/~sdn249/).
    It is related to a computational proof that elliptic curves are endowed with
    a group law.
    As [suggested](https://hal.inria.fr/inria-00129237v4/document) by Laurent
    Théry a while ago, this problem is a good benchmark for proof systems.
    Laurent Théry and Guillaume Hanrot [formally
    verified](https://doi.org/10.1007/978-3-540-74591-4_24) this property in Coq
    in 2007.

---
