---
fullname: Algebra Tactics
shortname: algebra-tactics
opam_name: coq-mathcomp-algebra-tactics
organization: math-comp
action: true

synopsis: >-
  Ring, field, lra, nra, and psatz tactics for Mathematical Components

description: |-
  This library provides `ring`, `field`, `lra`, `nra`, and `psatz` tactics for
  algebraic structures of the Mathematical Components library. The `ring` tactic
  works with any `comRingType` (commutative ring) or `comSemiRingType`
  (commutative semiring). The `field` tactic works with any `fieldType` (field).
  The other (Micromega) tactics work with any `realDomainType` (totally ordered
  integral domain) or `realFieldType` (totally ordered field). Algebra Tactics
  do not provide a way to declare instances, like the `Add Ring` and `Add Field`
  commands, but use canonical structure inference instead. Therefore, each of
  these tactics works with any canonical (or abstract) instance of the
  respective structure declared through Hierarchy Builder. Another key feature
  of Algebra Tactics is that they automatically push down ring morphisms and
  additive functions to leaves of ring/field expressions before applying the
  proof procedures.

publications:
- pub_url: https://drops.dagstuhl.de/opus/volltexte/2022/16738/
  pub_title: Reflexive tactics for algebra, revisited
  pub_doi: 10.4230/LIPIcs.ITP.2022.29

authors:
- name: Kazuhiko Sakaguchi
  initial: true
- name: Pierre Roux
  initial: false

opam-file-maintainer: kazuhiko.sakaguchi@inria.fr

license:
  fullname: CeCILL-B Free Software License Agreement
  identifier: CECILL-B
  file: CeCILL-B

supported_coq_versions:
  text: 8.16 or later
  opam: '{>= "8.16"}'

tested_coq_nix_versions:

tested_coq_opam_versions:
- version: '2.0.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '2.0.0-coq-8.17'
  repo: 'mathcomp/mathcomp'
- version: '2.0.0-coq-8.18'
  repo: 'mathcomp/mathcomp'
- version: 'coq-8.16'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.17'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.18'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{>= "2.0"}'
  description: |-
    [MathComp](https://math-comp.github.io) ssreflect 2.0 or later
- opam:
    name: coq-mathcomp-algebra
  description: |-
    [MathComp](https://math-comp.github.io) algebra
- opam:
    name: coq-mathcomp-zify
    version: '{>= "1.5.0"}'
  description: |-
    [Mczify](https://github.com/math-comp/mczify) 1.5.0 or later
- opam:
    name: coq-elpi
    version: '{>= "1.15.0" & != "1.17.0"}'
  description: |-
    [Coq-Elpi](https://github.com/LPCIC/coq-elpi) 1.15.0 or later (known not to work with 1.17.0)

namespace: mathcomp.algebra_tactics

documentation: |-
  ## Caveat

  The `lra`, `nra`, and `psatz` tactics are considered experimental features and
  subject to change.

  ## Credits

  - The adaptation of the `lra`, `nra`, and `psatz` tactics is contributed by
    Pierre Roux.
  - The way we adapt the internal lemmas of Coq's `ring` and `field` tactics to
    algebraic structures of the Mathematical Components library is inspired by
    the [elliptic-curves-ssr](https://github.com/strub/elliptic-curves-ssr)
    library by Evmorfia-Iro Bartzia and Pierre-Yves Strub.
  - The example [`from_sander.v`](examples/from_sander.v) contributed by Assia
    Mahboubi was given to her by [Sander Dahmen](http://www.few.vu.nl/~sdn249/).
    It is related to a computational proof that elliptic curves are endowed with
    a group law.
    As [suggested](https://hal.inria.fr/inria-00129237v4/document) by Laurent
    Théry a while ago, this problem is a good benchmark for proof systems.
    Laurent Théry and Guillaume Hanrot [formally
    verified](https://doi.org/10.1007/978-3-540-74591-4_24) this property in Coq
    in 2007.

---
